// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHqwCQoR3erw8EcMCKV5hMLFcg8HO0XLg',
    appId: '1:1542600288:web:703bf6c63d4a423aa7b505',
    messagingSenderId: '1542600288',
    projectId: 'technical-test-baguer',
    authDomain: 'technical-test-baguer.firebaseapp.com',
    storageBucket: 'technical-test-baguer.appspot.com',
    measurementId: 'G-8EDTRGLRWE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtmDEOtuV07KTZEn1B_GBRNZWTL3bX-O8',
    appId: '1:1542600288:android:3cdb61204ad1dd35a7b505',
    messagingSenderId: '1542600288',
    projectId: 'technical-test-baguer',
    storageBucket: 'technical-test-baguer.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAx2L-l_ku5IyRLQ4k813xurivwM3sGFe4',
    appId: '1:1542600288:ios:ecda4c8b99592b78a7b505',
    messagingSenderId: '1542600288',
    projectId: 'technical-test-baguer',
    storageBucket: 'technical-test-baguer.appspot.com',
    androidClientId: '1542600288-kiitp5bhhbmqd436t3n8khae3bqt6ijg.apps.googleusercontent.com',
    iosClientId: '1542600288-cu7u68qu1n1tj2k2gi64b84e6p8spe8v.apps.googleusercontent.com',
    iosBundleId: 'com.example.technicalTestBaguer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAx2L-l_ku5IyRLQ4k813xurivwM3sGFe4',
    appId: '1:1542600288:ios:ecda4c8b99592b78a7b505',
    messagingSenderId: '1542600288',
    projectId: 'technical-test-baguer',
    storageBucket: 'technical-test-baguer.appspot.com',
    androidClientId: '1542600288-kiitp5bhhbmqd436t3n8khae3bqt6ijg.apps.googleusercontent.com',
    iosClientId: '1542600288-cu7u68qu1n1tj2k2gi64b84e6p8spe8v.apps.googleusercontent.com',
    iosBundleId: 'com.example.technicalTestBaguer',
  );
}
